"""
Tests for the ONNX-based embedder (scoring/embedder.py).

Validates:
- Tokenizer loads cleanly
- embed_one returns correct dimensionality
- Vectors are L2-normalized
- Deterministic (same input → same output)
- Top-1 neighbor consistency against ground truth fixture
  (fixture generated by running this test once with the ONNX model;
   captures bge-small-en-v1.5 quantized cosine rankings)
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _cosine(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(x * x for x in b))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


def test_tokenizer_loads():
    """Tokenizer.from_file should succeed without network."""
    from scoring.embedder import _get_session
    session, tokenizer = _get_session()
    assert session is not None
    assert tokenizer is not None
    enc = tokenizer.encode("createOrder")
    assert len(enc.ids) > 0
    print("  tokenizer_loads: PASS")


def test_embed_one_dimensionality():
    """embed_one should return 384-dim vector (bge-small output)."""
    from scoring.embedder import embed_one
    vec = embed_one("createOrder")
    assert isinstance(vec, list), "Expected list"
    assert len(vec) == 384, f"Expected 384, got {len(vec)}"
    print("  embed_one_dimensionality: PASS (dim=384)")


def test_l2_norm():
    """Output vectors must be L2-normalized (norm ≈ 1.0)."""
    from scoring.embedder import embed_one
    vec = embed_one("createOrder")
    norm = math.sqrt(sum(x * x for x in vec))
    assert abs(norm - 1.0) < 1e-4, f"L2 norm should be ~1.0, got {norm}"
    print(f"  l2_norm: PASS (norm={norm:.6f})")


def test_determinism():
    """Same input must produce identical output."""
    from scoring.embedder import embed_one
    v1 = embed_one("createOrder")
    v2 = embed_one("createOrder")
    for i, (a, b) in enumerate(zip(v1, v2)):
        assert a == b, f"Mismatch at dim {i}: {a} != {b}"
    print("  determinism: PASS")


def test_batch_equals_single():
    """
    embed_texts([x]) and embed_one(x) must match (both use batch_size=1).
    Note: quantized ONNX models may produce ~5e-3 max diff when batch size changes
    (int8 quantization noise), so we only test the batch-size-1 case here.
    """
    from scoring.embedder import embed_one, embed_texts
    texts = ["createOrder", "userProfile", "kafka consumer"]
    for t in texts:
        batch1 = embed_texts([t])[0]
        single = embed_one(t)
        for j, (a, b) in enumerate(zip(batch1, single)):
            assert abs(a - b) < 1e-6, f"embed_texts([x])[0] vs embed_one(x) mismatch at text={t!r} dim={j}"
    print("  batch_equals_single: PASS")


def test_top1_neighbor_consistency():
    """
    Ground truth: top-1 neighbor rankings from ONNX model_quantized.onnx
    (Xenova/bge-small-en-v1.5). Generated empirically from the model.

    These fixtures ensure migration/version changes don't silently alter
    the embedding space — any correct quantized bge-small-en-v1.5 must
    reproduce the same cosine rankings.
    """
    from scoring.embedder import embed_texts

    # Corpus: 5 business terms from code navigation domain
    corpus = [
        "createOrder",       # 0
        "assignHomework",    # 1
        "userProfile",       # 2
        "paymentRefund",     # 3
        "kafkaConsumer",     # 4
    ]
    vecs = embed_texts(corpus)

    def top1(i):
        others = [j for j in range(len(corpus)) if j != i]
        return max(others, key=lambda j: _cosine(vecs[i], vecs[j]))

    results = {corpus[i]: corpus[top1(i)] for i in range(len(corpus))}
    print(f"  top1 neighbors: {results}")

    # Fixture verified against ONNX model_quantized.onnx (Xenova/bge-small-en-v1.5):
    # createOrder ↔ kafkaConsumer (highest cosine in this corpus for both)
    # assignHomework → createOrder
    # userProfile → assignHomework
    EXPECTED_TOP1 = {
        "createOrder": "kafkaConsumer",
        "assignHomework": "createOrder",
        "userProfile": "assignHomework",
        "paymentRefund": "createOrder",
        "kafkaConsumer": "createOrder",
    }
    for term, expected in EXPECTED_TOP1.items():
        actual = results[term]
        assert actual == expected, (
            f"{term} top1 should be {expected}, got {actual}. "
            f"The embedding model or quantization may have changed."
        )
    print("  top1_neighbor_consistency: PASS")


def test_cosine_range():
    """Cosines between distinct texts should be in [0, 1] for normalized vecs."""
    from scoring.embedder import embed_texts, cosine

    texts = ["createOrder", "kafkaConsumer", "userProfile"]
    vecs = embed_texts(texts)
    for i in range(len(texts)):
        for j in range(i + 1, len(texts)):
            c = cosine(vecs[i], vecs[j])
            assert 0.0 <= c <= 1.0, f"cosine({texts[i]}, {texts[j]}) = {c} out of [0,1]"
    print("  cosine_range: PASS")


def main():
    tests = [
        test_tokenizer_loads,
        test_embed_one_dimensionality,
        test_l2_norm,
        test_determinism,
        test_batch_equals_single,
        test_top1_neighbor_consistency,
        test_cosine_range,
    ]
    failed = 0
    for t in tests:
        try:
            t()
        except Exception as e:
            print(f"  {t.__name__}: FAIL — {e}")
            failed += 1

    print(f"\n{len(tests) - failed}/{len(tests)} ONNX embedder tests passed.")
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
